In [11]:
import numpy.matlib
import numpy as np

## Ones

In [12]:
np.matlib.ones((2,3), dtype = int)

matrix([[1, 1, 1],
        [1, 1, 1]])

## Zeros

In [10]:
a = np.matlib.zeros((3,2), dtype = int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


## eye() function

In [13]:
print(np.matlib.eye(n=3, M=4, k = 0, dtype = int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


## identity() Function

In [14]:
print(np.matlib.identity(5, dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## rand() Function

In [23]:
print(np.matlib.rand(3,3) * 10)

[[ 9.17668981  1.41304862  1.96047597]
 [ 7.31105819  9.28751088  6.76454688]
 [ 4.04210675  4.54019784  0.57335466]]


# Numpy Linear Algebra

In [20]:
a = np.matrix('1,2;3,4')
a

matrix([[1, 2],
        [3, 4]])

In [26]:
np.linalg.inv(a) #Inverse matrix of a

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [28]:
np.linalg.det(a) # Calculates the determinant

-2.0000000000000004

In [29]:
a = np.array([1,-2,3])
b = np.array([4,5,-3])

In [31]:
np.dot(a,b) #returns dot product of two arrays

-15

In [33]:
np.vdot(a,b)  #returns dot product of two vectors

-15

In [34]:
a = np.matrix('1,1,1;0,2,5;2,5,-1')
a

matrix([[ 1,  1,  1],
        [ 0,  2,  5],
        [ 2,  5, -1]])

x = transpose[x y z]

In [35]:
b = np.matrix('6;-4;27')
b

matrix([[ 6],
        [-4],
        [27]])

In [45]:
x = np.linalg.inv(a)*b
x

matrix([[ 5.],
        [ 3.],
        [-2.]])

In [49]:
print("******************")
a = np.matrix('1,3,-3;2,3,5')
print(a)
print(a.shape)
print("******************")
b = np.matrix('2,-3;4,2;5,-7')
print(b)
print(b.shape)
print("******************")
print("Multiplied matrix is")
print(np.matmul(a,b))


******************
[[ 1  3 -3]
 [ 2  3  5]]
(2, 3)
******************
[[ 2 -3]
 [ 4  2]
 [ 5 -7]]
(3, 2)
******************
Multiplied matrix is
[[ -1  24]
 [ 41 -35]]


In [50]:
print(np.matmul(b,a))

[[ -4  -3 -21]
 [  8  18  -2]
 [ -9  -6 -50]]


# NumPy Matplotlib Library

### Linear Equation Plot

In [54]:
from matplotlib import pyplot as plt
x = np.arange(1,11)
y = 3*x - 5
plt.title("Plotting the linear equation")
plt.xlabel("Values for x")
plt.ylabel("Values for y")
plt.plot(x,y)
plt.show()

### Sine Wave Plot

In [55]:
x = np.arange(0,3 * np.pi, 0.1)
y = np.sin(x)
plt.title("Sine Wave Plot")
plt.plot(x,y)
plt.show()

### Cosine Wave Plot

In [56]:
x = np.arange(0,3 * np.pi, 0.1)
y = np.cos(x)
plt.title("Cosine Wave Plot")
plt.plot(x,y)
plt.show()

### Tangent Wave Plot

In [57]:
x = np.arange(0,3 * np.pi, 0.1)
y = np.tan(x)
plt.title("Tangent Wave Plot")
plt.plot(x,y)
plt.show()

### Using subplot()

In [59]:
# for angles value
x = np.arange(0,3 * np.pi, 0.1)

# For sin wave
s = np.sin(x)
plt.subplot(3,1,1)
plt.plot(x,s)
plt.title("Sine Wave")
plt.xlabel("Values for x")
plt.ylabel("Values for y")

# For cos wave
c = np.cos(x)
plt.subplot(3,1,2)
plt.plot(x,c)
plt.title("Cosine Wave")
plt.xlabel("Values for x")
plt.ylabel("Values for y")

# For tan wave
t = np.tan(x)
plt.subplot(3,1,3)
plt.plot(x,t)
plt.title("Tangent Wave")
plt.xlabel("Values for x")
plt.ylabel("Values for y")
plt.show()

### Histogram Plot

In [62]:
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]) 
plt.hist(a, bins = [0,10,20,30,40,50,60,70,80,90,100]) 
plt.title("Histogram Plotting") 
plt.show()

## Save and Load Functions

In [63]:
a = np.array([2,3,5,7,11,13,17,19])
np.save('prime',a)

In [64]:
b = np.load('prime.npy')
print(b)

[ 2  3  5  7 11 13 17 19]


In [69]:
np.savetxt('prime.txt',a)
b = np.loadtxt('prime.txt')
print(b)

[  2.   3.   5.   7.  11.  13.  17.  19.]
