In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],
               [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


## Numpy Array Attributes

In [5]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Resizing the Array

In [6]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


#### Using Reshape function

In [7]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
c = b.reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


## Generating Array

In [9]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
y = x.reshape(4,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Numpy Flags

In [11]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [12]:
p = np.zeros(5)

In [13]:
print(p)

[ 0.  0.  0.  0.  0.]


In [14]:
q = np.ones(5)
print(q)

[ 1.  1.  1.  1.  1.]


In [15]:
r = np.ones(5,dtype=np.int)
print(r)

[1 1 1 1 1]


In [16]:
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


# Generating array from List

In [17]:
a = [x*x for x in range(20)]
print(a)
b = np.asarray(a) #using np.array() function
print(b)
print(b.reshape(5,4))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


# Generating array from Iterator 

In [18]:
import numpy as np 
list = [i for i in range(5)]
print(list)

[0, 1, 2, 3, 4]


In [19]:
a = np.fromiter(list, dtype = 'i4')
print(a)

[0 1 2 3 4]


# Generating an array from the Number Range

In [20]:
import numpy as np 
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


# numpy.linspace() Function

In [21]:
x = np.linspace(0,10,5)
print(x)

[  0.    2.5   5.    7.5  10. ]


In [22]:
x = np.linspace(0,10, 5, retstep = True) 
print(x)

(array([  0. ,   2.5,   5. ,   7.5,  10. ]), 2.5)


In [23]:
x = np.linspace(0,10, 5, endpoint = False) 
print(x)

[ 0.  2.  4.  6.  8.]


In [24]:
x = np.linspace(0,10, 5, endpoint = False, retstep = True) 
print(x)

(array([ 0.,  2.,  4.,  6.,  8.]), 2.0)


# numpy.logspace() Function

In [25]:
np.logspace(1,10,num=10,base=2)

array([    2.,     4.,     8.,    16.,    32.,    64.,   128.,   256.,
         512.,  1024.])

In [26]:
np.logspace(1,10,num=10,base=3)

array([  3.00000000e+00,   9.00000000e+00,   2.70000000e+01,
         8.10000000e+01,   2.43000000e+02,   7.29000000e+02,
         2.18700000e+03,   6.56100000e+03,   1.96830000e+04,
         5.90490000e+04])

# Indexing and Slicing in Numpy

In [27]:
b = [i for i in range(10)]
a = np.asarray(b)
print(a)
print(a[2])
print(a[6])
print(a[2:])
print(a[2:8:2])
print(a[:6])


[0 1 2 3 4 5 6 7 8 9]
2
6
[2 3 4 5 6 7 8 9]
[2 4 6]
[0 1 2 3 4 5]


# Custom Array

In [28]:
a = [x for x in range(6)]
b = [x*x for x in range(6)]
a.extend(b)
print(a)

[0, 1, 2, 3, 4, 5, 0, 1, 4, 9, 16, 25]


In [29]:
a = np.asarray(a).reshape(2,6)

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  1,  4,  9, 16, 25]])

In [31]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [32]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [33]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:' )
print(x) 
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:' )
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


# Broadcasting

In [34]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [35]:
a = np.array([[10,11,12],[20,21,22],[30,31,32],[40,41,42]])
c = a
b = np.array([1,2,3])
print(a+b)
print("\nCompare the Differences\n")
print(a+c)

[[11 13 15]
 [21 23 25]
 [31 33 35]
 [41 43 45]]

Compare the Differences

[[20 22 24]
 [40 42 44]
 [60 62 64]
 [80 82 84]]


# Iterating Over Array

In [36]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):  # nditer() is the function for iterating over an array.
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering.

In [37]:
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [38]:
b = a.T
print(b)
for x in np.nditer(b):
    print(x)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


# Some Array Functions

In [39]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a.flat[3]


4

In [40]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
# Transposing the function
print(a.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [42]:
# Returning the flat array
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
# Raveling the array
print(a.ravel(order='F'))
print(a.ravel(order='C'))
print(a.ravel(order='K'))

[ 1  6  2  7  3  8  4  9  5 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


#### rollaxis()

In [44]:
a = np.arange(8).reshape(2,2,2) 

print('The original array:' )
print(a)
print('\n')
# to roll axis-2 to axis-0 (along width to depth) 

print('After applying rollaxis function:')
print(np.rollaxis(a,2))
# to roll axis 0 to 1 (along width to height) 
print('\n')

print('After applying rollaxis function:')
print(np.rollaxis(a,2,1))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


After applying rollaxis function:
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


After applying rollaxis function:
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


###### swapaxes()

In [45]:
a = np.arange(8).reshape(2,2,2) 

print('The original array:')
print(a)
print('\n')
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print('The array after applying the swapaxes function:')
print(np.swapaxes(a, 2, 0))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


# Binary Operations in NumPy

#### bitwise_and & bitwise_or

In [46]:
a = 12
b = 13
print(bin(a))
print(bin(b))
print(bin(np.bitwise_and(a,b)))
print(bin(np.bitwise_or(a,b)))

0b1100
0b1101
0b1100
0b1101


#### invert, left_shift and right_shift

In [47]:
print(bin(a))
print("Left Shift by 2 Pos.")
x = np.left_shift(a,2)
print(bin(x))
print(x)
print("Right Shift by 2 Pos.")
y = np.right_shift(a,2)
print(bin(y))
print(y)
print("Inverting")
z = np.invert(a)
print(bin(z))
print(z)

0b1100
Left Shift by 2 Pos.
0b110000
48
Right Shift by 2 Pos.
0b11
3
Inverting
-0b1101
-13


# Other Functions

In [48]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [49]:
np.add(2,3)

5

In [50]:
np.multiply(3,4)

12

# Numpy Mathematical Functions

In [51]:
import numpy as np
a = np.array([0,30,45,60,90])
print("Sine values for different angles")
print(np.sin(a*np.pi/180))
print("Cosine values for different angles")
print(np.cos(a*np.pi/180))


Sine values for different angles
[ 0.          0.5         0.70710678  0.8660254   1.        ]
Cosine values for different angles
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


In [52]:
a = 0.5
deg = np.arcsin(a)
print(deg*180/np.pi)

30.0


Use arccos() and arctan() to calculate the inverses of cosine and tangent

In [53]:
# round() function
a = 30
b = np.cos(a*np.pi/180)
np.round(b,decimals = 3)

0.86599999999999999

In [54]:
# floor() function
b = 2.36
np.floor(b)

2.0

In [55]:
b = 3.99
np.floor(b)

3.0

In [56]:
np.ceil(b)

4.0

# Numpy Arithmetic Operations

In [57]:
a = np.array([2,3,4])
b = np.array([5,6,7])

In [58]:
np.add(a,b)

array([ 7,  9, 11])

In [59]:
np.subtract(a,b)

array([-3, -3, -3])

In [60]:
np.multiply(a,b)

array([10, 18, 28])

In [61]:
np.divide(a,b)

array([ 0.4       ,  0.5       ,  0.57142857])

In [62]:
x = np.arange(9,dtype = int).reshape(3,3)
y = np.array([10,10,10])

In [63]:
print(x)
print("\n")
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[10 10 10]


In [64]:
np.add(x,y)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [65]:
np.subtract(x,y)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [66]:
np.multiply(x,y)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [67]:
np.divide(x,y)

array([[ 0. ,  0.1,  0.2],
       [ 0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8]])

In [68]:
# np.reciprocal(x) calculates 1/x

In [69]:
np.reciprocal(x)

-c:1: RuntimeWarning: divide by zero encountered in reciprocal
-c:1: RuntimeWarning: invalid value encountered in reciprocal


array([[-9223372036854775808,                    1,                    0],
       [                   0,                    0,                    0],
       [                   0,                    0,                    0]])

In [70]:
np.reciprocal(y)

array([0, 0, 0])

In [71]:
np.power(x,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [72]:
a = np.array([10,30,50])
b = np.array([3,4,5])

In [73]:
np.mod(a,b)

array([1, 2, 0])

In [74]:
np.remainder(a,b)

array([1, 2, 0])

In [75]:
a = np.array([-1+2j,3.2j,1-2j,-3.2])

In [76]:
np.real(a)

array([-1. ,  0. ,  1. , -3.2])

In [77]:
np.imag(a)

array([ 2. ,  3.2, -2. ,  0. ])

In [78]:
np.conj(a)

array([-1.0-2.j ,  0.0-3.2j,  1.0+2.j , -3.2-0.j ])

In [79]:
np.angle(a, deg = True)

array([ 116.56505118,   90.        ,  -63.43494882,  180.        ])

# Numpy Statistical Functions

In [80]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [81]:
np.amin(a) #computes the minima

2

In [82]:
np.amax(a)

9

In [83]:
print(np.amax(a, axis = 0)) # calculates columnwise
print(np.amax(a, axis = 1)) #calculates rowwise

[8 7 9]
[7 8 9]


In [84]:
np.ptp(a) # calulates the range

7

In [85]:
print(np.ptp(a, axis = 0)) # calculates columnwise
print(np.ptp(a, axis = 1)) #calculates rowwise

[6 3 6]
[4 5 7]


In [86]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
print(a)

[[30 40 70]
 [80 20 10]
 [50 90 60]]


In [87]:
np.percentile(a,50)

50.0

In [88]:
print(np.percentile(a,50, axis = 0))

[ 50.  40.  60.]


In [89]:
print(np.percentile(a,50, axis = 1))

[ 40.  20.  60.]


In [90]:
np.median(a)

50.0

In [91]:
print(np.median(a,axis = 0))

[ 50.  40.  60.]


In [92]:
print(np.median(a,axis = 1))

[ 40.  20.  60.]


In [93]:
np.mean(a)

50.0

In [94]:
print(np.mean(a,axis = 0))

[ 53.33333333  50.          46.66666667]


In [95]:
print(np.mean(a,axis = 1))

[ 46.66666667  36.66666667  66.66666667]


In [96]:
np.average(a)

50.0

In [97]:
np.std(a)

25.819888974716111

In [98]:
np.var(a)

666.66666666666663

# ************ THE END ***********